title: Ife's Blog 
author: Ifenium
email: oyeif@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I post all i'm interested here when I'm not lazy.
theme: minima
# social links
twitter_username: ifenium # DO NOT include the @ character, or else the build will fail!
github_username:  ifenuim # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
